---
title: "Project"
author: "Aaron Niskin, Chris Leonard, Lance Price, Nicole Navarro"
date: "November 26, 2016"
output:
  pdf_document:
    highlight: tango
    toc: true
    toc_depth: 1
    number_sections: true
  documentclass: article
  classoption: titlepage
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='asis')
library(tidyverse)
library(xtable)
setwd("~/Documents/courses/newCollege/current/eda/projects/project2/")
printNamedDf <- function(df) {
  return(print.xtable(xtable(df), comment=FALSE))
}
printDf <- function(df) {
  return(print.xtable(xtable(df), comment=FALSE, include.rownames = FALSE))
}
```

test

```{r, results='hold'}
complications <- read.csv("ignore/Complications\ -\ Hospital.csv", na.strings = c("Not\ Available"))
ambulatorySurgical <- read.csv("ignore/Ambulatory\ Surgical\ Measures-Facility.csv", na.strings = c("Not\ Available"))
HCAHPS <- read.csv("ignore/HCAHPS\ -\ Hospital.csv", na.strings = c("Not\ Available"))
hvbp <- read.csv("ignore/hvbp_Efficiency_08_26_2016.csv", na.strings = c("Not\ Available"))
hvbp_ami <- read.csv("ignore/hvbp_ami_08_26_2016.csv", na.strings = c("Not\ Available"))
readmission <- read.csv("ignore/Readmissions\ and\ Deaths\ -\ Hospital.csv", na.strings = c("Not\ Available"))
timelyCare <- read.csv("ignore/Timely\ and\ Effective\ Care\ -\ Hospital.csv", na.strings = c("Not\ Available"))
readmissionReduction <- read.csv("ignore/READMISSION\ REDUCTION.csv", na.strings = c("Not\ Available"))
infections <- read.csv("ignore/Healthcare\ Associated\ Infections\ -\ Hospital.csv", na.strings = c("Not\ Available"))
spending <- read.csv("ignore/Medicare\ Hospital\ Spending\ by\ Claim.csv", na.strings = c("Not\ Available"))
spending <- read.csv("ignore/Medicare\ Hospital\ Spending\ by\ Claim.csv", na.strings = c("Not\ Available"))
```



So far it seems like the best variables to use might be the ones from the `spending` table, `readmissionReduction`, `timelyCare`, `readmission`, `complications`, and `ambulatorySurgical`.